[package]
name = "yew-sample-app"
version = "0.1.0"
authors = ["zeppilabs <zeppilabs@protonmail.ch>"]
edition = "2018"

[dependencies]
yew = "0.18"
log = "0.4"
wasm-logger = "0.2"
web-sys = "0.3.52"
wasm-bindgen = "0.2.75"